In [9]:
from sklearn.datasets import load_iris
import numpy as np
import random
iris=load_iris()
x=iris.data
y=iris.target


In [ ]:
def train_test_split(x,y,seed):
    np.random.seed(seed)
    combined=list(zip(x,y))
    random.shuffle(combined)
    x_shuffled,y_shuffled=zip(*combined)
    train_ratio=0.8
    train_idx=int(len(x_shuffled)*train_ratio)
    x_train=x_shuffled[:train_idx]
    y_train=y_shuffled[:train_idx]
    x_test=x_shuffled[train_idx:]
    y_test=x_shuffled[train_idx:]
    return x_train,y_train,x_test,y_test
x_train,y_train,x_test,y_test=train_test_split(x,y,23)




(array([5. , 3.5, 1.6, 0.6]), array([4.5, 2.3, 1.3, 0.3]), array([6.4, 3.1, 5.5, 1.8]), array([5.5, 2.3, 4. , 1.3]), array([5.5, 4.2, 1.4, 0.2]), array([5.4, 3.9, 1.3, 0.4]), array([5. , 2. , 3.5, 1. ]), array([7.2, 3.6, 6.1, 2.5]), array([5.2, 3.5, 1.5, 0.2]), array([4.3, 3. , 1.1, 0.1]), array([5. , 3. , 1.6, 0.2]), array([4.4, 3. , 1.3, 0.2]), array([6.5, 3. , 5.5, 1.8]), array([6.5, 3. , 5.8, 2.2]), array([6.9, 3.2, 5.7, 2.3]), array([5.9, 3. , 5.1, 1.8]), array([5.7, 2.8, 4.5, 1.3]), array([6.3, 3.4, 5.6, 2.4]), array([5.6, 2.8, 4.9, 2. ]), array([6.3, 3.3, 4.7, 1.6]), array([7.7, 3.8, 6.7, 2.2]), array([5.8, 2.7, 5.1, 1.9]), array([6. , 2.9, 4.5, 1.5]), array([7.2, 3. , 5.8, 1.6]), array([6.1, 3. , 4.9, 1.8]), array([6.8, 3. , 5.5, 2.1]), array([5.3, 3.7, 1.5, 0.2]), array([6.1, 2.8, 4. , 1.3]), array([4.9, 3. , 1.4, 0.2]), array([7.1, 3. , 5.9, 2.1]), array([5.4, 3.7, 1.5, 0.2]), array([4.8, 3. , 1.4, 0.1]), array([5.8, 2.8, 5.1, 2.4]), array([6.5, 3.2, 5.1, 2. ]), array([5.5, 2

In [ ]:
w=np.random.randn(3,4)
b=np.


[[ 0.66698806  0.02581308 -0.77761941  0.94863382]
 [ 0.70167179 -1.05108156 -0.36754812 -1.13745969]
 [-1.32214752  1.77225828 -0.34745899  0.67014016]]
